# Comments

In [1]:
# This is my comment

In [2]:
#= This is a multiline comment
lets start Julia from here
All the best =#

# Numbers And Variables

In [5]:
10

10

In [6]:
4.5

4.5

In [7]:
typeof(10)

Int64

In [8]:
typeof(4.5)

Float64

In [9]:
10 + 20

30

In [10]:
num1 = 10

10

In [11]:
num1

10

In [12]:
println(num1)

10


In [13]:
num2 = 20

20

In [14]:
num1 + num2

30

In [15]:
num1 * num2

200

In [16]:
num1 ^ num2

7766279631452241920

# Strings

In [17]:
"Hello World"

"Hello World"

In [18]:
'Hello World'

LoadError: syntax: invalid character literal

In [19]:
my_str = "Hellow World"

"Hellow World"

In [20]:
typeof(my_str)

String

In [21]:
println(my_str)

Hellow World


In [22]:
mult_str = """My multiline
    string assignment
    lets check it"""

"My multiline\nstring assignment\nlets check it"

In [23]:
println(mult_str)

My multiline
string assignment
lets check it


In [24]:
newstr = """hello "user" string"""

"hello \"user\" string"

In [25]:
newstr

"hello \"user\" string"

In [26]:
println(newstr)

hello "user" string


In [33]:
# Concatenation
s1 = "Hello"
s2 = "World"
string(s1, s2)

"HelloWorld"

In [34]:
string(s1,"newuser",s2)

"HellonewuserWorld"

In [35]:
s1 * s2

"HelloWorld"

In [37]:
s1 ^ 5

"HelloHelloHelloHelloHello"

In [38]:
s1[1]

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [39]:
s1[2:4]

"ell"

In [40]:
# Character
mychar = 'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [41]:
typeof(mychar)

Char

In [42]:
mychar = 'ab'

LoadError: syntax: invalid character literal

# Arrays

In [43]:
my_arr = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [44]:
typeof(my_arr)

Array{Int64,1}

In [45]:
length(my_arr)

3

In [46]:
maximum(my_arr)

3

In [47]:
my_arr1 = [1, "Hello", 10, 4.5]

4-element Array{Any,1}:
  1
   "Hello"
 10
  4.5

In [48]:
my_arr1[2]

"Hello"

In [49]:
my_arr1[2:4]

3-element Array{Any,1}:
   "Hello"
 10
  4.5

In [50]:
println(my_arr1)

Any[1, "Hello", 10, 4.5]


In [51]:
push!(my_arr, 5)

4-element Array{Int64,1}:
 1
 2
 3
 5

In [54]:
my_arr

4-element Array{Int64,1}:
 1
 2
 3
 5

In [55]:
arr = [10, -5, 7, 0]

4-element Array{Int64,1}:
 10
 -5
  7
  0

In [56]:
sort(arr)

4-element Array{Int64,1}:
 -5
  0
  7
 10

In [57]:
a1 = arr

4-element Array{Int64,1}:
 10
 -5
  7
  0

In [58]:
a1

4-element Array{Int64,1}:
 10
 -5
  7
  0

In [59]:
arr[1] = 11

11

In [60]:
a1

4-element Array{Int64,1}:
 11
 -5
  7
  0

# Control Flow

In [63]:
num = 10

10

In [71]:
num = 5
if num > 5
    println("Greater")
elseif num < 5     
    println("Lesser")
else
    println("Equals")   
end

Equals


# Loops

In [72]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [75]:
i = 1
while i <= 5
    println(i)
    i = i +1
end

1
2
3
4
5


In [86]:
# Nested loop
for i = 1:5
    for j = 1:5
        println(i, j)
    end
end

11
12
13
14
15
21
22
23
24
25
31
32
33
34
35
41
42
43
44
45
51
52
53
54
55


In [87]:
5 > 4

true

In [88]:
5 > 6

false

# Tuples

In [94]:
t = (1 , 2, 3)

(1, 2, 3)

In [95]:
typeof(t)

Tuple{Int64,Int64,Int64}

In [96]:
t[2]

2

In [97]:
println(t)

(1, 2, 3)


In [98]:
t[2] = 5

MethodError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [99]:
length(t)

3

# Dictionaries

In [100]:
Dict("abc" => "123", "def" => "456", "xyz" => "789")

Dict{String,String} with 3 entries:
  "abc" => "123"
  "def" => "456"
  "xyz" => "789"

In [107]:
my_dict = Dict("abc" => "123", "def" => "456", "xyz" => "789")

Dict{String,String} with 3 entries:
  "abc" => "123"
  "def" => "456"
  "xyz" => "789"

In [108]:
typeof(my_dict)

Dict{String,String}

In [109]:
my_dict["abc"]

"123"

In [110]:
keys(my_dict)

Base.KeySet for a Dict{String,String} with 3 entries. Keys:
  "abc"
  "def"
  "xyz"

In [111]:
values(my_dict)

Base.ValueIterator for a Dict{String,String} with 3 entries. Values:
  "123"
  "456"
  "789"

In [113]:
for(key, values) in my_dict
    println("$key", "$values")
end

abc123
def456
xyz789


In [114]:
haskey(my_dict, "abc")

true

In [115]:
haskey(my_dict, "abc1")

false

# Sets

In [116]:
Set([1,2,3])

Set{Int64} with 3 elements:
  2
  3
  1

In [117]:
my_set = Set([1,2,3])

Set{Int64} with 3 elements:
  2
  3
  1

In [118]:
typeof(my_set)

Set{Int64}

In [120]:
my_set = Set([1,2,3,3,2,2,4])

Set{Int64} with 4 elements:
  4
  2
  3
  1

# Functions

In [121]:
function hello()
    println("Hello World")
end

hello (generic function with 1 method)

In [122]:
hello()

Hello World


In [124]:
#Parameterized function
function hello_user(name)
    println("Hello $name")
end

hello_user("def")

Hello def


In [125]:
# Return statement
function sum(num1, num2)
    num = num1 + num2
    return num
end

sum (generic function with 1 method)

In [126]:
sum(10,20)

30

# Packages

In [127]:
using Pkg

In [128]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/Pkg/src/Pkg.jl:531


Dict{String,VersionNumber} with 12 entries:
  "CSV"               => v"0.3.1"
  "Atom"              => v"0.12.10"
  "Juno"              => v"0.8.1"
  "HTTP"              => v"0.8.14"
  "PyCall"            => v"1.91.4"
  "Weave"             => v"0.9.4"
  "IJulia"            => v"1.20.0"
  "Plots"             => v"1.2.2"
  "PyPlot"            => v"2.9.0"
  "DataFrames"        => v"0.21.0"
  "PlotlyJS"          => v"0.12.92"
  "PkgAuthentication" => v"0.1.2"

In [129]:
Pkg.add("Random")

   Updating registry at `~/.juliapro/JuliaPro_v1.4.1-1/registries/JuliaPro`
######################################################################### 100.0%                                              38.2%
  Resolving package versions...
  Installed Cassette ─ v0.3.3
   Updating `~/.juliapro/JuliaPro_v1.4.1-1/environments/v1.4/Project.toml`
  [9a3f8284] + Random 
   Updating `~/.juliapro/JuliaPro_v1.4.1-1/environments/v1.4/Manifest.toml`
  [7057c7e9] + Cassette v0.3.3
  [fb4132e2] - FuzzyCompletions v0.1.0
  [98e50ef6] ↓ JuliaFormatter v0.5.1 ⇒ v0.3.9
  [37b6cedf] + Traceur v0.3.0


In [132]:
Pkg.rm("Random")

   Updating `~/.juliapro/JuliaPro_v1.4.1-1/environments/v1.4/Project.toml`
  [9a3f8284] - Random 
   Updating `~/.juliapro/JuliaPro_v1.4.1-1/environments/v1.4/Manifest.toml`
 [no changes]


In [133]:
using DataFrames

┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1260


In [134]:
using Random

In [135]:
rand(1,100)

1×100 Array{Float64,2}:
 0.299856  0.437439  0.0578412  0.253006  …  0.350911  0.684697  0.83148

In [138]:
randstring(20)

"TEaMBimXF52thyv4gnyn"

# Vectors and Matrices

In [139]:
v = Vector(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [141]:
reshape(v, 2, 5)

2×5 Array{Int64,2}:
 1  3  5  7   9
 2  4  6  8  10

In [142]:
zeros(3, 5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [143]:
ones(3, 5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [147]:
using LinearAlgebra

In [148]:
mat1 = [1 2 3 ; 4 5 6 ; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [149]:
typeof(mat1)

Array{Int64,2}

In [150]:
size(mat1)

(3, 3)

In [151]:
mat1[1,2]

2

In [152]:
mat1[2,:]

3-element Array{Int64,1}:
 4
 5
 6

In [153]:
mat1[:,2]

3-element Array{Int64,1}:
 2
 5
 8

In [155]:
mat2 = [9 8 7; 6 5 4; 3 2 1]

3×3 Array{Int64,2}:
 9  8  7
 6  5  4
 3  2  1

In [156]:
#Concatenate
[ mat1 mat2]

3×6 Array{Int64,2}:
 1  2  3  9  8  7
 4  5  6  6  5  4
 7  8  9  3  2  1

In [157]:
[ mat1 ; mat2]

6×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9
 9  8  7
 6  5  4
 3  2  1

In [158]:
hcat(mat1, mat2)

3×6 Array{Int64,2}:
 1  2  3  9  8  7
 4  5  6  6  5  4
 7  8  9  3  2  1

In [159]:
vcat(mat1, mat2)

6×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9
 9  8  7
 6  5  4
 3  2  1

In [161]:
# Transpose 
transpose(mat1)

3×3 Transpose{Int64,Array{Int64,2}}:
 1  4  7
 2  5  8
 3  6  9